variables:
  CUSTOM_CI_BUILDS_DIR: /p/scratch/slen/clausen1

stages:
  - prepare
  - benchmark

jusuf_login:
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  stage: prepare
  tags:
    - jusuf
    - jacamar
    - login
    - shell
  script:
    - module load Python/3.12.3
    - module load git
    - export MY_JOB_PREFIX=/p/scratch/slen/clausen1/cb-libertem-$CI_PIPELINE_ID
    - mkdir -p $MY_JOB_PREFIX/

    # main run:
    - export TOX_WORK_DIR=$MY_JOB_PREFIX/tox-main
    - python3 -m venv $MY_JOB_PREFIX/venv-main
    - $MY_JOB_PREFIX/venv-main/bin/pip install tox-uv uv
    - $MY_JOB_PREFIX/venv-main/bin/tox -e benchmark-cb -- --help  # only create
    - pwd
    - ls -la

    # reference run:
    - export TOX_WORK_DIR=$MY_JOB_PREFIX/tox-ref
    - git clone https://github.com/LiberTEM/LiberTEM.git $MY_JOB_PREFIX/git-ref --depth=10
    - cd $MY_JOB_PREFIX/git-ref
    - git log -n 10 --oneline
    - git rev-parse HEAD
    - python3 -m venv $MY_JOB_PREFIX/venv-ref
    - $MY_JOB_PREFIX/venv-ref/bin/pip install tox-uv uv
    - $MY_JOB_PREFIX/venv-ref/bin/tox -e benchmark-cb -- --help  # only create
    - pwd
    - ls -la

# TODO: update job names (to something generic) - for now kept like this for the comparison script

juwels_cpu:
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  variables:
    SCHEDULER_PARAMETERS: '--account=slen -N1 --cpus-per-task 128 --partition=batch --disable-turbomode --cpufreq=2250'
  stage: benchmark
  tags:
    - jusuf
    - jacamar
    - compute
    - slurm
  script:
    - module load Python/3.12.3
    - module load git
    - export MY_JOB_PREFIX=/p/scratch/slen/clausen1/cb-libertem-$CI_PIPELINE_ID
    - export TOX_WORK_DIR=$MY_JOB_PREFIX/tox-main
    - pwd
    - ls -la
    - $MY_JOB_PREFIX/venv-main/bin/tox -e benchmark-cb
  artifacts:
    paths:
      - bench-results.json

juwels_cpu_reference_run:
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  variables:
    SCHEDULER_PARAMETERS: '--account=slen -N1 --cpus-per-task 128 --partition=batch --disable-turbomode --cpufreq=2250'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^PullRequest_/
  stage: benchmark
  tags:
    - jusuf
    - jacamar
    - compute
    - slurm
  script:
    - module load git
    - module load Python/3.12.3
    - export MY_JOB_PREFIX=/p/scratch/slen/clausen1/cb-libertem-$CI_PIPELINE_ID
    - export TOX_WORK_DIR=$MY_JOB_PREFIX/tox-ref
    - cd $MY_JOB_PREFIX/git-ref
    - pwd
    - ls -la
    - $MY_JOB_PREFIX/venv-ref/bin/tox -e benchmark-cb
  artifacts:
    paths:
      - bench-results.json

# vim:ts=2:sw=2
