variables:
  CUSTOM_CI_BUILDS_DIR: /p/scratch/slen/clausen1

stages:
  - prepare
  - benchmark

jusuf_login:
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  stage: prepare
  tags:
    - jusuf
    - jacamar
    - login
    - shell
  script:
    - module load Python/3.12.3
    - module load git

    # main run:
    - python3 -m venv venv
    - ./venv/bin/pip install tox-uv uv
    - ./venv/bin/tox -e benchmark-cb -- --help  # only create
    - pwd
    - ls -la

    # reference run:
    - git clone https://github.com/LiberTEM/LiberTEM.git ref --depth=10
    - cd ref
    - git log -n 10 --oneline
    - git rev-parse HEAD
    - python3 -m venv venv
    - ./venv/bin/pip install tox-uv uv
    - ./venv/bin/tox -e benchmark-cb -- --help  # only create
    - pwd
    - ls -la

# TODO: update job names (to something generic) - for now kept like this for the comparison script

juwels_cpu:
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  variables:
    SCHEDULER_PARAMETERS: '--account=slen -N1 --cpus-per-task 128 --partition=batch --disable-turbomode --cpufreq=2200'
  stage: benchmark
  tags:
    - jusuf
    - jacamar
    - compute
    - slurm
  script:
    - module load Python/3.12.3
    - module load git
    - pwd
    - ls -la
    - ./venv/bin/tox -e benchmark-cb
  artifacts:
    paths:
      - bench-results.json

juwels_cpu_reference_run:
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  variables:
    SCHEDULER_PARAMETERS: '--account=slen -N1 --cpus-per-task 128 --partition=batch --disable-turbomode --cpufreq=2200'
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^PullRequest_/
  stage: benchmark
  tags:
    - jusuf
    - jacamar
    - compute
    - slurm
  script:
    - module load git
    - module load Python/3.12.3
    - cd ref
    - pwd
    - ls -la
    - ./venv/bin/tox -e benchmark-cb
  artifacts:
    paths:
      - bench-results.json

# vim:ts=2:sw=2
