comment:
  # check_example_notebooks
  # data_tests * 3
  # linux_tests * 4
  # numba_coverage
  # node_tests
  after_n_builds: 10
coverage:
  status:
    project:
      default:
        threshold: 1
codecov:
  token: 9636efc6-7fff-40a5-91a7-d835cd22ecf9
