version: "3.4"

services:
  scheduler:
    build:
      context: ../../
      dockerfile: packaging/docker/Dockerfile
    ports:
      - "8786:8786"
      - "8787:8787"
    image: libertem/libertem
    command: ["/venv/bin/dask-scheduler"]
  worker-1:
    build:
      context: ../../
      dockerfile: packaging/docker/Dockerfile
    hostname: worker-1
    image: libertem/libertem
    command: ["/venv/bin/dask-worker", "tcp://scheduler:8786", "--nthreads", "1", "--nprocs", "2"]
    volumes:
      - type: bind
        source: ../../data
        target: /data
  worker-2:
    build:
      context: ../../
      dockerfile: packaging/docker/Dockerfile
    hostname: worker-2
    image: libertem/libertem
    command: ["/venv/bin/dask-worker", "tcp://scheduler:8786", "--nthreads", "1", "--nprocs", "2"]
    volumes:
      - type: bind
        source: ../../data
        target: /data
