# syntax=docker/dockerfile:1.0.0-experimental
FROM libertem/libertem:continuous AS builder

COPY test_requirements.txt /test_requirements.txt
RUN /venv/bin/pip install --no-cache -r /test_requirements.txt && /venv/bin/pip install ipyparallel

FROM builder

COPY --from=builder /venv/ /venv/
COPY --from=builder /code/ /code/

ENV PYTHONUNBUFFERED 1

CMD ["/venv/bin/libertem-server"]

# vim:ft=dockerfile
