all: unpack-12-6 unpack-12-4

unpack-12-4:
	gcc -Wall -o unpack-12-4 expected.cpp unpack-12-4.cpp harness.cpp

unpack-12-6:
	gcc -Wall -o unpack-12-6 expected.cpp unpack-12-6.cpp harness.cpp

clean:
	rm -f unpack-12-4 unpack-12-6
