#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import json

with open('packaging/contributors.json', 'rb') as f:
    contributors = json.load(f)

with open('packaging/creators.json', 'rb') as f:
    creators = json.load(f)

creators = sorted(creators, key=lambda c: c['authorname'])
contributors = sorted(contributors, key=lambda c: c['authorname'])


def format_entry(a):
    entry = "**"
    if 'displayname' in a:
        entry += a['displayname']
    if 'affiliation' in a:
        entry += " (%s)" % a['affiliation']
    entry += "**"
    if 'orcid' in a:
        entry += " `ORCID <https://orcid.org/%s>`__" % a['orcid']
    if 'github' in a:
        entry += " `GitHub <https://github.com/%s>`__" % a['github']

    if 'contribution' in a:
        entry += "\n    %s" % a['contribution']

    entry += "\n\n"
    return entry


with open('docs/source/creators.rst', 'w', encoding='utf-8') as f:
    for c in creators:
        f.write(format_entry(c))

with open('docs/source/contributors.rst', 'w', encoding='utf-8') as f:
    for c in contributors:
        f.write(format_entry(c))
