name: CI

on:
  push:
    branches:
      - master
      - 'v[0-9]*'
    tags:
      - 'v[0-9]*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-15, ubuntu-latest]
        python_version: ["3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Choose Python version ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python_version }}'
          cache: 'pip'
      - name: install dependencies
        run: python3 -m pip install numpy numba
      - name: run script
        run: python tests/test_tmp_numbastuff.py
