name: CI

on:
  push:
    branches:
      - master
      - 'v[0-9]*'
    tags:
      - 'v[0-9]*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-15]
        python:
          - version: "3.13"
            toxenv: py313-quick
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Choose Python version ${{ matrix.python.version }}
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python.version }}'
          cache: 'pip'
      - run: |
           [[ "${{ matrix.os }}" = "ubuntu-latest" ]] && sudo apt-get install -y libcap-dev || true
        shell: bash
      - name: install dependencies
        run: python3 -m pip install numba 
      - name: run script
        run: tox -e '${{ matrix.python.toxenv }}'
