name: Thorough (manual)

on:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-14]
        python:
          - version: "3.9"
            toxenv: py39
          - version: "3.10"
            toxenv: py310
          - version: "3.11"
            toxenv: py311
          - version: "3.12"
            toxenv: py312
          - version: "3.13"
            toxenv: py313
        exclude:
          - os: macos-14
            python:
              version: "3.9"
              toxenv: py39

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Choose Python version ${{ matrix.python.version }}
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python.version }}'
          cache: 'pip'
      - run: |
           [[ "${{ matrix.os }}" = "ubuntu-latest" ]] && sudo apt-get install -y libcap-dev || true
        shell: bash
      - name: install tox (with uv)
        run: python3 -m pip install tox tox-uv
      - name: run tox
        run: tox -e '${{ matrix.python.toxenv }}' -- tests/ -m "not dist"
