name: trigger libertem.github.io rebuild

on:
  push:
    branches:
      - master
#     paths:
#       - 'packaging/*'


jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST -u "sk1p:${{secrets.PAGES_TRIGGER_GH_TOKEN}}" -H 'Accept: application/vnd.github.everest-preview+json' -H 'Content-Type: application/json' https://api.github.com/repos/LiberTEM/libertem.github.io/dispatches --data '{"event_type": "build_application"}'
